title: Bingxin Su's Homepage
page-top-title: Bingxin Su
top-section-bg-text: Be what you wanna be
home-subtitle: Bingxin Su&ensp;|&ensp; Undergraduate @ HIT Weihai
copyright-text: '&copy; Bingxin Su 2024-2026. All Rights Reserved.'
